# Use the official TensorFlow Serving image as the base image
FROM tensorflow/serving:latest

# Copy the TensorFlow SavedModel into the container
COPY ./models /models

# Set environment variables
ENV MODEL_NAME=captcha-ocr-model